const data = {
  products: [
    {
      category: "coffee",
      image: "/images/guatemala-coffee.jpeg",
      id: "Chimaltenango",
      origin: "Guatemala",
      farm: "Chimaltenango Tecpan",
      variety: "Bourbon",
      process: "natural",
      price: "18.00",
      elevation: 1750,
      tasting_notes: "Chocolate, Candied Almond, and Cane Sugar",
    },
    {
      category: "coffee",
      image: "/images/ethiopia-coffee.jpeg",
      id: "Yirgacheffe",
      origin: "Ethiopia",
      farm: "Yirgacheffe",
      variety: "Heirloom",
      process: "natural",
      price: "19.00",
      elevation: 2000,
      tasting_notes: "Blueberry, Chocolate, and Lemon",
    },
    {
      category: "coffee",
      image: "/images/kenya-coffee.jpeg",
      id: "Kirinyaga",
      origin: "Kenya",
      farm: "Kirinyaga",
      variety: "SL-28",
      process: "washed",
      price: "21.00",
      elevation: 1850,
      tasting_notes: "Pomegranate, Blackberry, and Cane Sugar",
    },
    {
      category: "coffee",
      image: "/images/guatemala-coffee.jpeg",
      id: "Chimaltenango",
      origin: "Guatemala",
      farm: "Chimaltenango Tecpan",
      variety: "Bourbon",
      process: "natural",
      price: "18.00",
      elevation: 1750,
      tasting_notes: "Chocolate, Candied Almond, and Cane Sugar",
    },
    {
      category: "coffee",
      image: "/images/ethiopia-coffee.jpeg",
      id: "Yirgacheffe",
      origin: "Ethiopia",
      farm: "Yirgacheffe",
      variety: "Heirloom",
      process: "natural",
      price: "19.00",
      elevation: 2000,
      tasting_notes: "Blueberry, Chocolate, and Lemon",
    },
    {
      category: "coffee",
      image: "/images/kenya-coffee.jpeg",
      id: "Kirinyaga",
      origin: "Kenya",
      farm: "Kirinyaga",
      variety: "SL-28",
      process: "washed",
      price: "21.00",
      elevation: 1850,
      tasting_notes: "Pomegranate, Blackberry, and Cane Sugar",
    },
  ],
};

export default data;
